/*
 * Generated by `scripts/gen-theme-presets.mjs` — do not edit by hand.
 *
 * Source: the theme customizer on shadcn-svelte.com, vendored at
 * `scripts/theme-presets/shadcn-themes.json`. Run the generator to re-sync.
 *
 * A base colour is a whole palette; an accent replaces only the brand triplet
 * on top of it. That is upstream's own split — you pick a base colour, then a
 * theme within it — and it is why picking "Blue" does not turn the sidebar blue.
 */

/** One theme's contribution: CSS custom property name to value. */
export type ThemeTokens = Record<string, string>

export interface ThemePreset {
  name: string
  title: string
  /**
   * The dot shown beside the name in settings — base colours only, whose own
   * `--brand` is a contrast step rather than a hue and would say nothing.
   */
  swatch?: string
  light: ThemeTokens
  dark: ThemeTokens
}

export const BASE_COLORS: ThemePreset[] = [
  {
    "name": "neutral",
    "title": "Neutral",
    "swatch": "#737373",
    "light": {
      "--bg": "oklch(1 0 0)",
      "--bg-raised": "oklch(1 0 0)",
      "--bg-sunken": "oklch(0.97 0 0)",
      "--bg-hover": "oklch(0.951 0 0)",
      "--bg-active": "oklch(0.922 0 0)",
      "--border": "oklch(0.922 0 0)",
      "--border-strong": "oklch(0.87 0 0)",
      "--text": "oklch(0.145 0 0)",
      "--text-muted": "oklch(0.556 0 0)",
      "--text-faint": "oklch(0.665 0 0)",
      "--brand": "oklch(0.205 0 0)",
      "--brand-on": "oklch(0.985 0 0)",
      "--brand-soft": "oklch(0.94 0 0)",
      "--tooltip": "oklch(0.269 0 0)",
      "--tooltip-on": "oklch(0.985 0 0)",
      "--check-tick": "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='none' stroke='%23949494' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='m4 8.2 2.8 2.8 5.2-5.2'/%3E%3C/svg%3E\")"
    },
    "dark": {
      "--bg": "oklch(0.145 0 0)",
      "--bg-raised": "oklch(0.205 0 0)",
      "--bg-sunken": "oklch(0.185 0 0)",
      "--bg-hover": "oklch(0.269 0 0)",
      "--bg-active": "oklch(0.32 0 0)",
      "--border": "oklch(0.285 0 0)",
      "--border-strong": "oklch(0.38 0 0)",
      "--text": "oklch(0.985 0 0)",
      "--text-muted": "oklch(0.708 0 0)",
      "--text-faint": "oklch(0.556 0 0)",
      "--brand": "oklch(0.922 0 0)",
      "--brand-on": "oklch(0.205 0 0)",
      "--brand-soft": "oklch(0.3 0 0)",
      "--tooltip": "oklch(0.32 0 0)",
      "--tooltip-on": "oklch(0.985 0 0)",
      "--check-tick": "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='none' stroke='%23737373' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='m4 8.2 2.8 2.8 5.2-5.2'/%3E%3C/svg%3E\")"
    }
  },
  {
    "name": "stone",
    "title": "Stone",
    "swatch": "#79716B",
    "light": {
      "--bg": "oklch(1 0 0)",
      "--bg-raised": "oklch(1 0 0)",
      "--bg-sunken": "oklch(0.97 0.001 106.424)",
      "--bg-hover": "oklch(0.951 0.001 106.424)",
      "--bg-active": "oklch(0.922 0.003 48.717)",
      "--border": "oklch(0.922 0.003 48.717)",
      "--border-strong": "oklch(0.87 0.003 48.717)",
      "--text": "oklch(0.145 0.004 49.25)",
      "--text-muted": "oklch(0.556 0.013 58.071)",
      "--text-faint": "oklch(0.665 0.01 56.259)",
      "--brand": "oklch(0.205 0.006 56.043)",
      "--brand-on": "oklch(0.985 0.001 106.423)",
      "--brand-soft": "oklch(0.94 0.003 48.717)",
      "--tooltip": "oklch(0.269 0.006 56.043)",
      "--tooltip-on": "oklch(0.985 0.001 106.423)",
      "--check-tick": "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='none' stroke='%2399928e' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='m4 8.2 2.8 2.8 5.2-5.2'/%3E%3C/svg%3E\")"
    },
    "dark": {
      "--bg": "oklch(0.145 0.004 49.25)",
      "--bg-raised": "oklch(0.205 0.006 56.043)",
      "--bg-sunken": "oklch(0.185 0.006 56.043)",
      "--bg-hover": "oklch(0.269 0.007 34.298)",
      "--bg-active": "oklch(0.32 0.007 34.298)",
      "--border": "oklch(0.285 0.007 34.298)",
      "--border-strong": "oklch(0.38 0.007 34.298)",
      "--text": "oklch(0.985 0.001 106.423)",
      "--text-muted": "oklch(0.708 0.01 56.259)",
      "--text-faint": "oklch(0.556 0.013 58.071)",
      "--brand": "oklch(0.922 0.003 48.717)",
      "--brand-on": "oklch(0.205 0.006 56.043)",
      "--brand-soft": "oklch(0.3 0.007 34.298)",
      "--tooltip": "oklch(0.32 0.007 34.298)",
      "--tooltip-on": "oklch(0.985 0.001 106.423)",
      "--check-tick": "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='none' stroke='%2379726c' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='m4 8.2 2.8 2.8 5.2-5.2'/%3E%3C/svg%3E\")"
    }
  },
  {
    "name": "zinc",
    "title": "Zinc",
    "swatch": "#71717B",
    "light": {
      "--bg": "oklch(1 0 0)",
      "--bg-raised": "oklch(1 0 0)",
      "--bg-sunken": "oklch(0.97 0.001 286.375)",
      "--bg-hover": "oklch(0.951 0.001 286.375)",
      "--bg-active": "oklch(0.922 0.004 286.32)",
      "--border": "oklch(0.922 0.004 286.32)",
      "--border-strong": "oklch(0.87 0.004 286.32)",
      "--text": "oklch(0.145 0.005 285.823)",
      "--text-muted": "oklch(0.556 0.016 285.938)",
      "--text-faint": "oklch(0.665 0.015 286.067)",
      "--brand": "oklch(0.205 0.006 285.885)",
      "--brand-on": "oklch(0.985 0 0)",
      "--brand-soft": "oklch(0.94 0.004 286.32)",
      "--tooltip": "oklch(0.269 0.006 285.885)",
      "--tooltip-on": "oklch(0.985 0 0)",
      "--check-tick": "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='none' stroke='%2393939d' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='m4 8.2 2.8 2.8 5.2-5.2'/%3E%3C/svg%3E\")"
    },
    "dark": {
      "--bg": "oklch(0.145 0.005 285.823)",
      "--bg-raised": "oklch(0.205 0.006 285.885)",
      "--bg-sunken": "oklch(0.185 0.006 285.885)",
      "--bg-hover": "oklch(0.269 0.006 286.033)",
      "--bg-active": "oklch(0.32 0.006 286.033)",
      "--border": "oklch(0.285 0.006 286.033)",
      "--border-strong": "oklch(0.38 0.006 286.033)",
      "--text": "oklch(0.985 0 0)",
      "--text-muted": "oklch(0.708 0.015 286.067)",
      "--text-faint": "oklch(0.556 0.016 285.938)",
      "--brand": "oklch(0.922 0.004 286.32)",
      "--brand-on": "oklch(0.205 0.006 285.885)",
      "--brand-soft": "oklch(0.3 0.006 286.033)",
      "--tooltip": "oklch(0.32 0.006 286.033)",
      "--tooltip-on": "oklch(0.985 0 0)",
      "--check-tick": "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='none' stroke='%2372727d' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='m4 8.2 2.8 2.8 5.2-5.2'/%3E%3C/svg%3E\")"
    }
  },
  {
    "name": "mauve",
    "title": "Mauve",
    "swatch": "#79697B",
    "light": {
      "--bg": "oklch(1 0 0)",
      "--bg-raised": "oklch(1 0 0)",
      "--bg-sunken": "oklch(0.97 0.003 325.6)",
      "--bg-hover": "oklch(0.951 0.003 325.6)",
      "--bg-active": "oklch(0.922 0.005 325.62)",
      "--border": "oklch(0.922 0.005 325.62)",
      "--border-strong": "oklch(0.87 0.005 325.62)",
      "--text": "oklch(0.145 0.008 326)",
      "--text-muted": "oklch(0.556 0.034 322.5)",
      "--text-faint": "oklch(0.665 0.019 323.02)",
      "--brand": "oklch(0.205 0.019 322.12)",
      "--brand-on": "oklch(0.985 0 0)",
      "--brand-soft": "oklch(0.94 0.005 325.62)",
      "--tooltip": "oklch(0.269 0.019 322.12)",
      "--tooltip-on": "oklch(0.985 0 0)",
      "--check-tick": "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='none' stroke='%239a909b' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='m4 8.2 2.8 2.8 5.2-5.2'/%3E%3C/svg%3E\")"
    },
    "dark": {
      "--bg": "oklch(0.145 0.008 326)",
      "--bg-raised": "oklch(0.205 0.019 322.12)",
      "--bg-sunken": "oklch(0.185 0.019 322.12)",
      "--bg-hover": "oklch(0.269 0.024 320.12)",
      "--bg-active": "oklch(0.32 0.024 320.12)",
      "--border": "oklch(0.285 0.024 320.12)",
      "--border-strong": "oklch(0.38 0.024 320.12)",
      "--text": "oklch(0.985 0 0)",
      "--text-muted": "oklch(0.708 0.019 323.02)",
      "--text-faint": "oklch(0.556 0.034 322.5)",
      "--brand": "oklch(0.922 0.005 325.62)",
      "--brand-on": "oklch(0.205 0.019 322.12)",
      "--brand-soft": "oklch(0.3 0.024 320.12)",
      "--tooltip": "oklch(0.32 0.024 320.12)",
      "--tooltip-on": "oklch(0.985 0 0)",
      "--check-tick": "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='none' stroke='%237d6d7f' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='m4 8.2 2.8 2.8 5.2-5.2'/%3E%3C/svg%3E\")"
    }
  },
  {
    "name": "olive",
    "title": "Olive",
    "swatch": "#7C7C67",
    "light": {
      "--bg": "oklch(1 0 0)",
      "--bg-raised": "oklch(1 0 0)",
      "--bg-sunken": "oklch(0.97 0.005 106.5)",
      "--bg-hover": "oklch(0.951 0.005 106.5)",
      "--bg-active": "oklch(0.922 0.007 106.5)",
      "--border": "oklch(0.922 0.007 106.5)",
      "--border-strong": "oklch(0.87 0.007 106.5)",
      "--text": "oklch(0.145 0.006 107.1)",
      "--text-muted": "oklch(0.556 0.031 107.3)",
      "--text-faint": "oklch(0.665 0.021 106.9)",
      "--brand": "oklch(0.205 0.013 107.4)",
      "--brand-on": "oklch(0.985 0.003 106.5)",
      "--brand-soft": "oklch(0.94 0.007 106.5)",
      "--tooltip": "oklch(0.269 0.013 107.4)",
      "--tooltip-on": "oklch(0.985 0.003 106.5)",
      "--check-tick": "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='none' stroke='%23959586' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='m4 8.2 2.8 2.8 5.2-5.2'/%3E%3C/svg%3E\")"
    },
    "dark": {
      "--bg": "oklch(0.145 0.006 107.1)",
      "--bg-raised": "oklch(0.205 0.013 107.4)",
      "--bg-sunken": "oklch(0.185 0.006 107.1)",
      "--bg-hover": "oklch(0.269 0.016 107.4)",
      "--bg-active": "oklch(0.32 0.016 107.4)",
      "--border": "oklch(0.285 0.016 107.4)",
      "--border-strong": "oklch(0.38 0.016 107.4)",
      "--text": "oklch(0.985 0.003 106.5)",
      "--text-muted": "oklch(0.708 0.021 106.9)",
      "--text-faint": "oklch(0.556 0.031 107.3)",
      "--brand": "oklch(0.922 0.007 106.5)",
      "--brand-on": "oklch(0.205 0.013 107.4)",
      "--brand-soft": "oklch(0.3 0.016 107.4)",
      "--tooltip": "oklch(0.32 0.016 107.4)",
      "--tooltip-on": "oklch(0.985 0.003 106.5)",
      "--check-tick": "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='none' stroke='%23757560' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='m4 8.2 2.8 2.8 5.2-5.2'/%3E%3C/svg%3E\")"
    }
  },
  {
    "name": "mist",
    "title": "Mist",
    "swatch": "#67787C",
    "light": {
      "--bg": "oklch(1 0 0)",
      "--bg-raised": "oklch(1 0 0)",
      "--bg-sunken": "oklch(0.97 0.002 197.1)",
      "--bg-hover": "oklch(0.951 0.002 197.1)",
      "--bg-active": "oklch(0.922 0.005 214.3)",
      "--border": "oklch(0.922 0.005 214.3)",
      "--border-strong": "oklch(0.87 0.005 214.3)",
      "--text": "oklch(0.145 0.004 228.8)",
      "--text-muted": "oklch(0.556 0.021 213.5)",
      "--text-faint": "oklch(0.665 0.014 214.4)",
      "--brand": "oklch(0.205 0.008 223.9)",
      "--brand-on": "oklch(0.985 0.002 197.1)",
      "--brand-soft": "oklch(0.94 0.005 214.3)",
      "--tooltip": "oklch(0.269 0.008 223.9)",
      "--tooltip-on": "oklch(0.985 0.002 197.1)",
      "--check-tick": "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='none' stroke='%238b9699' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='m4 8.2 2.8 2.8 5.2-5.2'/%3E%3C/svg%3E\")"
    },
    "dark": {
      "--bg": "oklch(0.145 0.004 228.8)",
      "--bg-raised": "oklch(0.205 0.008 223.9)",
      "--bg-sunken": "oklch(0.185 0.008 223.9)",
      "--bg-hover": "oklch(0.269 0.011 216.9)",
      "--bg-active": "oklch(0.32 0.011 216.9)",
      "--border": "oklch(0.285 0.011 216.9)",
      "--border-strong": "oklch(0.38 0.011 216.9)",
      "--text": "oklch(0.985 0.002 197.1)",
      "--text-muted": "oklch(0.708 0.014 214.4)",
      "--text-faint": "oklch(0.556 0.021 213.5)",
      "--brand": "oklch(0.922 0.005 214.3)",
      "--brand-on": "oklch(0.205 0.008 223.9)",
      "--brand-soft": "oklch(0.3 0.011 216.9)",
      "--tooltip": "oklch(0.32 0.011 216.9)",
      "--tooltip-on": "oklch(0.985 0.002 197.1)",
      "--check-tick": "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='none' stroke='%2366777b' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='m4 8.2 2.8 2.8 5.2-5.2'/%3E%3C/svg%3E\")"
    }
  },
  {
    "name": "taupe",
    "title": "Taupe",
    "swatch": "#7C6D67",
    "light": {
      "--bg": "oklch(1 0 0)",
      "--bg-raised": "oklch(1 0 0)",
      "--bg-sunken": "oklch(0.97 0.002 17.2)",
      "--bg-hover": "oklch(0.951 0.002 17.2)",
      "--bg-active": "oklch(0.922 0.005 34.3)",
      "--border": "oklch(0.922 0.005 34.3)",
      "--border-strong": "oklch(0.87 0.005 34.3)",
      "--text": "oklch(0.145 0.004 49.3)",
      "--text-muted": "oklch(0.556 0.021 43.1)",
      "--text-faint": "oklch(0.665 0.014 41.2)",
      "--brand": "oklch(0.205 0.009 43.1)",
      "--brand-on": "oklch(0.985 0.002 67.8)",
      "--brand-soft": "oklch(0.94 0.005 34.3)",
      "--tooltip": "oklch(0.269 0.009 43.1)",
      "--tooltip-on": "oklch(0.985 0.002 67.8)",
      "--check-tick": "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='none' stroke='%239c918d' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='m4 8.2 2.8 2.8 5.2-5.2'/%3E%3C/svg%3E\")"
    },
    "dark": {
      "--bg": "oklch(0.145 0.004 49.3)",
      "--bg-raised": "oklch(0.205 0.009 43.1)",
      "--bg-sunken": "oklch(0.185 0.009 43.1)",
      "--bg-hover": "oklch(0.269 0.011 36.5)",
      "--bg-active": "oklch(0.32 0.011 36.5)",
      "--border": "oklch(0.285 0.011 36.5)",
      "--border-strong": "oklch(0.38 0.011 36.5)",
      "--text": "oklch(0.985 0.002 67.8)",
      "--text-muted": "oklch(0.708 0.014 41.2)",
      "--text-faint": "oklch(0.556 0.021 43.1)",
      "--brand": "oklch(0.922 0.005 34.3)",
      "--brand-on": "oklch(0.205 0.009 43.1)",
      "--brand-soft": "oklch(0.3 0.011 36.5)",
      "--tooltip": "oklch(0.32 0.011 36.5)",
      "--tooltip-on": "oklch(0.985 0.002 67.8)",
      "--check-tick": "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='none' stroke='%237f706a' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='m4 8.2 2.8 2.8 5.2-5.2'/%3E%3C/svg%3E\")"
    }
  }
]

export const ACCENTS: ThemePreset[] = [
  {
    "name": "amber",
    "title": "Amber",
    "light": {
      "--brand": "oklch(0.473 0.137 46.201)",
      "--brand-on": "oklch(0.985 0.02 46.201)",
      "--brand-soft": "oklch(0.94 0.0343 46.201)"
    },
    "dark": {
      "--brand": "oklch(0.879 0.169 91.605)",
      "--brand-on": "oklch(0.205 0.03 91.605)",
      "--brand-soft": "oklch(0.3 0.0423 91.605)"
    }
  },
  {
    "name": "blue",
    "title": "Blue",
    "light": {
      "--brand": "oklch(0.424 0.199 265.638)",
      "--brand-on": "oklch(0.985 0.02 265.638)",
      "--brand-soft": "oklch(0.94 0.0498 265.638)"
    },
    "dark": {
      "--brand": "oklch(0.809 0.105 251.813)",
      "--brand-on": "oklch(0.205 0.03 251.813)",
      "--brand-soft": "oklch(0.3 0.0262 251.813)"
    }
  },
  {
    "name": "cyan",
    "title": "Cyan",
    "light": {
      "--brand": "oklch(0.45 0.085 224.283)",
      "--brand-on": "oklch(0.985 0.02 224.283)",
      "--brand-soft": "oklch(0.94 0.0213 224.283)"
    },
    "dark": {
      "--brand": "oklch(0.865 0.127 207.078)",
      "--brand-on": "oklch(0.205 0.03 207.078)",
      "--brand-soft": "oklch(0.3 0.0318 207.078)"
    }
  },
  {
    "name": "emerald",
    "title": "Emerald",
    "light": {
      "--brand": "oklch(0.432 0.095 166.913)",
      "--brand-on": "oklch(0.985 0.02 166.913)",
      "--brand-soft": "oklch(0.94 0.0238 166.913)"
    },
    "dark": {
      "--brand": "oklch(0.845 0.143 164.978)",
      "--brand-on": "oklch(0.205 0.03 164.978)",
      "--brand-soft": "oklch(0.3 0.0357 164.978)"
    }
  },
  {
    "name": "fuchsia",
    "title": "Fuchsia",
    "light": {
      "--brand": "oklch(0.452 0.211 324.591)",
      "--brand-on": "oklch(0.985 0.02 324.591)",
      "--brand-soft": "oklch(0.94 0.05 324.591)"
    },
    "dark": {
      "--brand": "oklch(0.833 0.145 321.434)",
      "--brand-on": "oklch(0.205 0.03 321.434)",
      "--brand-soft": "oklch(0.3 0.0362 321.434)"
    }
  },
  {
    "name": "green",
    "title": "Green",
    "light": {
      "--brand": "oklch(0.448 0.119 151.328)",
      "--brand-on": "oklch(0.985 0.02 151.328)",
      "--brand-soft": "oklch(0.94 0.0297 151.328)"
    },
    "dark": {
      "--brand": "oklch(0.871 0.15 154.449)",
      "--brand-on": "oklch(0.205 0.03 154.449)",
      "--brand-soft": "oklch(0.3 0.0375 154.449)"
    }
  },
  {
    "name": "indigo",
    "title": "Indigo",
    "light": {
      "--brand": "oklch(0.457 0.24 277.023)",
      "--brand-on": "oklch(0.985 0.02 277.023)",
      "--brand-soft": "oklch(0.94 0.05 277.023)"
    },
    "dark": {
      "--brand": "oklch(0.785 0.115 274.713)",
      "--brand-on": "oklch(0.205 0.03 274.713)",
      "--brand-soft": "oklch(0.3 0.0288 274.713)"
    }
  },
  {
    "name": "lime",
    "title": "Lime",
    "light": {
      "--brand": "oklch(0.453 0.124 130.933)",
      "--brand-on": "oklch(0.985 0.02 130.933)",
      "--brand-soft": "oklch(0.94 0.031 130.933)"
    },
    "dark": {
      "--brand": "oklch(0.768 0.233 130.85)",
      "--brand-on": "oklch(0.205 0.03 130.85)",
      "--brand-soft": "oklch(0.3 0.0583 130.85)"
    }
  },
  {
    "name": "orange",
    "title": "Orange",
    "light": {
      "--brand": "oklch(0.47 0.157 37.304)",
      "--brand-on": "oklch(0.985 0.02 37.304)",
      "--brand-soft": "oklch(0.94 0.0393 37.304)"
    },
    "dark": {
      "--brand": "oklch(0.837 0.128 66.29)",
      "--brand-on": "oklch(0.205 0.03 66.29)",
      "--brand-soft": "oklch(0.3 0.032 66.29)"
    }
  },
  {
    "name": "pink",
    "title": "Pink",
    "light": {
      "--brand": "oklch(0.459 0.187 3.815)",
      "--brand-on": "oklch(0.985 0.02 3.815)",
      "--brand-soft": "oklch(0.94 0.0467 3.815)"
    },
    "dark": {
      "--brand": "oklch(0.823 0.12 346.018)",
      "--brand-on": "oklch(0.205 0.03 346.018)",
      "--brand-soft": "oklch(0.3 0.03 346.018)"
    }
  },
  {
    "name": "purple",
    "title": "Purple",
    "light": {
      "--brand": "oklch(0.438 0.218 303.724)",
      "--brand-on": "oklch(0.985 0.02 303.724)",
      "--brand-soft": "oklch(0.94 0.05 303.724)"
    },
    "dark": {
      "--brand": "oklch(0.827 0.119 306.383)",
      "--brand-on": "oklch(0.205 0.03 306.383)",
      "--brand-soft": "oklch(0.3 0.0297 306.383)"
    }
  },
  {
    "name": "red",
    "title": "Red",
    "light": {
      "--brand": "oklch(0.444 0.177 26.899)",
      "--brand-on": "oklch(0.985 0.02 26.899)",
      "--brand-soft": "oklch(0.94 0.0442 26.899)"
    },
    "dark": {
      "--brand": "oklch(0.808 0.114 19.571)",
      "--brand-on": "oklch(0.205 0.03 19.571)",
      "--brand-soft": "oklch(0.3 0.0285 19.571)"
    }
  },
  {
    "name": "rose",
    "title": "Rose",
    "light": {
      "--brand": "oklch(0.455 0.188 13.697)",
      "--brand-on": "oklch(0.985 0.02 13.697)",
      "--brand-soft": "oklch(0.94 0.047 13.697)"
    },
    "dark": {
      "--brand": "oklch(0.81 0.117 11.638)",
      "--brand-on": "oklch(0.205 0.03 11.638)",
      "--brand-soft": "oklch(0.3 0.0293 11.638)"
    }
  },
  {
    "name": "sky",
    "title": "Sky",
    "light": {
      "--brand": "oklch(0.443 0.11 240.79)",
      "--brand-on": "oklch(0.985 0.02 240.79)",
      "--brand-soft": "oklch(0.94 0.0275 240.79)"
    },
    "dark": {
      "--brand": "oklch(0.828 0.111 230.318)",
      "--brand-on": "oklch(0.205 0.03 230.318)",
      "--brand-soft": "oklch(0.3 0.0278 230.318)"
    }
  },
  {
    "name": "teal",
    "title": "Teal",
    "light": {
      "--brand": "oklch(0.437 0.078 188.216)",
      "--brand-on": "oklch(0.985 0.02 188.216)",
      "--brand-soft": "oklch(0.94 0.0195 188.216)"
    },
    "dark": {
      "--brand": "oklch(0.855 0.138 181.071)",
      "--brand-on": "oklch(0.205 0.03 181.071)",
      "--brand-soft": "oklch(0.3 0.0345 181.071)"
    }
  },
  {
    "name": "violet",
    "title": "Violet",
    "light": {
      "--brand": "oklch(0.432 0.232 292.759)",
      "--brand-on": "oklch(0.985 0.02 292.759)",
      "--brand-soft": "oklch(0.94 0.05 292.759)"
    },
    "dark": {
      "--brand": "oklch(0.811 0.111 293.571)",
      "--brand-on": "oklch(0.205 0.03 293.571)",
      "--brand-soft": "oklch(0.3 0.0278 293.571)"
    }
  },
  {
    "name": "yellow",
    "title": "Yellow",
    "light": {
      "--brand": "oklch(0.476 0.114 61.907)",
      "--brand-on": "oklch(0.985 0.02 61.907)",
      "--brand-soft": "oklch(0.94 0.0285 61.907)"
    },
    "dark": {
      "--brand": "oklch(0.795 0.184 86.047)",
      "--brand-on": "oklch(0.205 0.03 86.047)",
      "--brand-soft": "oklch(0.3 0.046 86.047)"
    }
  }
]

/**
 * Corner rounding, upstream's five steps.
 *
 * `default` is 0.5rem, which is what `app.css` already declares — so the
 * default choice writes the value the stylesheet was going to use anyway.
 */
export const RADII: Array<{ name: string; title: string; value: string }> = [
  {
    "name": "none",
    "title": "None",
    "value": "0rem"
  },
  {
    "name": "small",
    "title": "Small",
    "value": "0.45rem"
  },
  {
    "name": "default",
    "title": "Default",
    "value": "0.5rem"
  },
  {
    "name": "medium",
    "title": "Medium",
    "value": "0.625rem"
  },
  {
    "name": "large",
    "title": "Large",
    "value": "0.875rem"
  }
]
